// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using marmitariaLeozitos.Data;

#nullable disable

namespace marmitariaLeozitos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250405154350_PedidoMarmita")]
    partial class PedidoMarmita
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("marmitariaLeozitos.Models.Marmita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Marmita");
                });

            modelBuilder.Entity("marmitariaLeozitos.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("marmitariaLeozitos.Models.PedidoMarmita", b =>
                {
                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("MarmitaId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("PedidoId", "MarmitaId");

                    b.HasIndex("MarmitaId");

                    b.ToTable("PedidoMarmita");
                });

            modelBuilder.Entity("marmitariaLeozitos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("marmitariaLeozitos.Models.Pedido", b =>
                {
                    b.HasOne("marmitariaLeozitos.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("marmitariaLeozitos.Models.PedidoMarmita", b =>
                {
                    b.HasOne("marmitariaLeozitos.Models.Marmita", "Marmita")
                        .WithMany()
                        .HasForeignKey("MarmitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("marmitariaLeozitos.Models.Pedido", "Pedido")
                        .WithMany("PedidoMarmita")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marmita");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("marmitariaLeozitos.Models.Pedido", b =>
                {
                    b.Navigation("PedidoMarmita");
                });

            modelBuilder.Entity("marmitariaLeozitos.Models.Usuario", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
